version: '3'

services:
  mobile-web-do:
    container_name: mobile-web-do
    restart: always
    build: .
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: mongodb://mongo:27017/mobile-web-do
      AUTH_CLIENT_ID: {AUTH_CLIENT_ID}
      AUTH_DOMAIN: {AUTH_DOMAIN}
      AUTH_CALLBACK_URL: {AUTH_CALLBACK_URL}
    links:
      - mongo
    ports:
      - 3000:3000
    networks:
      - mwdnet
    depends_on:
      - mongo
  mongo:
    container_name: mobile-web-do_storage
    image: mongo
    volumes:
      - ../data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mwdnet
networks:
  mwdnet: